### PR TITLE
Kykrueger issue3

### PR DESCRIPTION
**Pull request by kykrueger**
relates to #3

### CODE REVIEW

**Comment by pulsargranular** [comment]
Yes, I guess caching experiments makes sense, as they usually don't change very often. I am happy to implement that, too. You can expect a new pyBIS version this week.
Cheers, Swen

**Comment by kykrueger** [comment]
That is great news. I'll close this as soon as we are able to use the feature in an official release.

**Comment by pulsargranular** [comment]
@kykrueger This caching has also been implemented in the new release of pyBIS 1.19.0. Have a nice day!

**Comment by kykrueger** [comment]
@pulsargranular thanks!

**Pull request closed without merging**
