### PR TITLE
allow OR based search of samples given codes

### PR DESCRIPTION
**Pull request by kykrueger**

### CODE REVIEW

**Comment by pulsargranular** [comment]
This is a good idea! It has already implemented in the get_sample() method, but not yet in the get_samples() method, which makes more sense.
Cheers, Swen

**Comment by kykrueger** [comment]
@pulsargranular I was not able to get this working myself as an additional feature for get_samples. Instead I created a helper function in our project which uses some of your hidden functions as a workaround for now.

Will you be adding this, or should I take a look at get_sample, and try to figure out how you did it there?

**Comment by pulsargranular** [comment]
@kykrueger I now just released a new PyBIS version (1.19.0) which implements this:

```
o.get_samples(permId=['20210317134746710-1', '20210317134811746-19'])
o.get_samples(code=['DEFAULT', 'BENCH'])
```

Works similarly with dataSets, of course with `permId` only. Hope that helps! (If not, please let me know).

**Comment by kykrueger** [comment]
This is perfect, thanks for the quick changes. Now we can clean up our pipeline by using the native commands. Thanks again

**Pull request closed without merging**
